import { readFile, mkdir, copyFile, chmod, writeFile } from 'node:fs/promises';
import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { resolve } from 'node:path';
const expected = { 'linux-x86_64':['linux','x64'], 'macos-x86_64':['darwin','x64'], 'macos-aarch64':['darwin','arm64'], 'windows-x86_64':['win32','x64'] };
const platform = process.argv[2];
if (!expected[platform] || expected[platform][0] !== process.platform || expected[platform][1] !== process.arch) throw Error('Runner architecture does not match package name');
const suffix = process.platform === 'win32' ? '.exe' : '';
const source = `native/target/release/aximo-voice-native${suffix}`;
const name = `aximo-voice-native-${platform}${suffix}`;
await mkdir('dist',{recursive:true});
const target = resolve('dist',name);
await copyFile(source,target);await chmod(target,0o755);
const version = JSON.parse(execFileSync(target,['--version'],{encoding:'utf8'}));
const doctor = JSON.parse(execFileSync(target,['doctor'],{encoding:'utf8'}));
if (version.version !== '0.1.0' || doctor.type !== 'doctor' || doctor.microphoneChecked !== false) throw Error('Relocated helper doctor/version contract failed');
let dependencies = '';
if (process.platform === 'linux') dependencies=execFileSync('ldd',[target],{encoding:'utf8'});
if (process.platform === 'darwin') dependencies=execFileSync('otool',['-L',target],{encoding:'utf8'});
if (/not found|target\/release|libonnxruntime|@rpath\/libonnxruntime/i.test(dependencies)) throw Error('Helper requires an unbundled runtime library; package and installer must be updated before release');
const sha=createHash('sha256').update(await readFile(target)).digest('hex');
await writeFile(`dist/${name}.sha256`,`${sha}  ${name}\n`);
await writeFile(`dist/${name}.build.json`,JSON.stringify({version:version.version,platform,commit:process.env.GITHUB_SHA||null,sha256:sha,doctor,dependencies,unsigned:true,microphoneTested:false},null,2)+'\n');
console.log(`${name}: relocated executable verified, SHA-256 ${sha}`);
